/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Footer: typeof import('./src/components/footer.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Intro: typeof import('./src/components/intro.vue')['default']
    Map: typeof import('./src/components/map.vue')['default']
    Popover: typeof import('primevue/popover')['default']
    SplitButton: typeof import('primevue/splitbutton')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
  }
}
