/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Aaland: typeof import('./src/components/aaland.vue')['default']
    Blaavand: typeof import('./src/components/blaavand.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Intro: typeof import('./src/components/intro.vue')['default']
    SwiperMap: typeof import('./src/components/swiper-map.vue')['default']
    Vasterbotten: typeof import('./src/components/vasterbotten.vue')['default']
    Vestkystruten: typeof import('./src/components/vestkystruten.vue')['default']
  }
}
