/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Footer: typeof import('./src/components/footer.vue')['default']
    Header: typeof import('./src/components/header.vue')['default']
    Map: typeof import('./src/components/map.vue')['default']
    MapSwitch: typeof import('./src/components/map-switch.vue')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
  }
}
